name: docker-hive CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-hive:$(date +%s)
    
    - uses: plexsystems/container-structure-test-action@v0.1.0
    - name: Test the Docker image
      with: 
        image: docker-hive:$(date +%s)
        config: test-config.yaml
